added 2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,17 +29,22 @@ jobs:
           PORT: ${{ secrets.PORT }}
         run: |
           ssh $USER@$HOST << 'EOF'
-            set -e  # xatolikda chiqib ketsin
+            set -e
 
-            if [ ! -d $APP_DIR ]; then
-              mkdir -p $APP_DIR
-              git clone https://github.com/muhammadaliteacher/xn_3_ci_cd_deploy.git $APP_DIR
-            else
-              cd $APP_DIR
-              git pull origin main
+            if [ ! -d "$APP_DIR" ]; then
+              mkdir -p "$APP_DIR"
+              git clone https://github.com/muhammadaliteacher/xn_3_ci_cd_deploy.git "$APP_DIR"
             fi
 
-            cd $APP_DIR
+            cd "$APP_DIR"
+
+            if [ ! -d .git ]; then
+              echo "❌ Repo not cloned properly. Aborting."
+              exit 1
+            fi
+
+            git pull origin main
+
             echo "PORT=$PORT" > .env
             npm install
             npm run build
